//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_Archive")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveEntity : FormEntity<E_SupplierIdentification_PartnerUserLast_ArchiveEntity> {
        
        private E_SupplierIdentification_PartnerUserLast_ArchiveVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDCEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity> _RDC;
        
        public E_SupplierIdentification_PartnerUserLast_ArchiveEntity() {
            this.VersionEntity = new E_SupplierIdentification_PartnerUserLast_ArchiveVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDCEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity>();
        }
        
        public E_SupplierIdentification_PartnerUserLast_ArchiveVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_PartnerUserLast_ArchiveRDCEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_ArchiveVR")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveVREntity : VersionEntity<E_SupplierIdentification_PartnerUserLast_ArchiveVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_ArchiveRDC")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveRDCEntity : RDCEntity<E_SupplierIdentification_PartnerUserLast_ArchiveRDCEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_ArchiveRDCML")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity : RDCMLEntity<E_SupplierIdentification_PartnerUserLast_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_ArchiveRD")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveRDEntity : RDEntity<E_SupplierIdentification_PartnerUserLast_ArchiveRDEntity, E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserLast_ArchiveRDML")]
    public class E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity : RDMLEntity<E_SupplierIdentification_PartnerUserLast_ArchiveRDMLEntity> {
    }
}




