//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_Archive")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveEntity : FormEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveEntity> {
        
        private E_SupplierIdentification_ConsultingDefinition2_ArchiveVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveMLEntity> _ML;
        
        public E_SupplierIdentification_ConsultingDefinition2_ArchiveEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_ConsultingDefinition2_ArchiveVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity>();
        }
        
        public E_SupplierIdentification_ConsultingDefinition2_ArchiveVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_ConsultingDefinition2_ArchiveMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveML")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveMLEntity : MLEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _FILTERPARAMS;
        
        [ColumnOptionsAttribute(Name="FILTERPARAMS", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> FILTERPARAMS {
            get {
                return this._FILTERPARAMS;
            }
            set {
                this._FILTERPARAMS = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveVR")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveVREntity : VersionEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveRDC")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCEntity : RDCEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCML")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity : RDCMLEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveRD")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveRDEntity : RDEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDEntity, E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition2_ArchiveRDML")]
    public class E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity : RDMLEntity<E_SupplierIdentification_ConsultingDefinition2_ArchiveRDMLEntity> {
    }
}




