//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_Archive")]
    public class E_SupplierIdentification_Solutions_ArchiveEntity : FormEntity<E_SupplierIdentification_Solutions_ArchiveEntity> {
        
        private E_SupplierIdentification_Solutions_ArchiveVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDEntity, E_SupplierIdentification_Solutions_ArchiveRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDCEntity, E_SupplierIdentification_Solutions_ArchiveRDCMLEntity> _RDC;
        
        public E_SupplierIdentification_Solutions_ArchiveEntity() {
            this.VersionEntity = new E_SupplierIdentification_Solutions_ArchiveVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDEntity, E_SupplierIdentification_Solutions_ArchiveRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDCEntity, E_SupplierIdentification_Solutions_ArchiveRDCMLEntity>();
        }
        
        public E_SupplierIdentification_Solutions_ArchiveVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDEntity, E_SupplierIdentification_Solutions_ArchiveRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_Solutions_ArchiveRDCEntity, E_SupplierIdentification_Solutions_ArchiveRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_ArchiveVR")]
    public class E_SupplierIdentification_Solutions_ArchiveVREntity : VersionEntity<E_SupplierIdentification_Solutions_ArchiveVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_ArchiveRDC")]
    public class E_SupplierIdentification_Solutions_ArchiveRDCEntity : RDCEntity<E_SupplierIdentification_Solutions_ArchiveRDCEntity, E_SupplierIdentification_Solutions_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_ArchiveRDCML")]
    public class E_SupplierIdentification_Solutions_ArchiveRDCMLEntity : RDCMLEntity<E_SupplierIdentification_Solutions_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_ArchiveRD")]
    public class E_SupplierIdentification_Solutions_ArchiveRDEntity : RDEntity<E_SupplierIdentification_Solutions_ArchiveRDEntity, E_SupplierIdentification_Solutions_ArchiveRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_Solutions_ArchiveRDML")]
    public class E_SupplierIdentification_Solutions_ArchiveRDMLEntity : RDMLEntity<E_SupplierIdentification_Solutions_ArchiveRDMLEntity> {
    }
}




