//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition")]
    public class E_SupplierIdentification_ConsultingDefinitionEntity : FormEntity<E_SupplierIdentification_ConsultingDefinitionEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _ACTIVITY;
        
        private E_SupplierIdentification_ConsultingDefinitionVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDEntity, E_SupplierIdentification_ConsultingDefinitionRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDCEntity, E_SupplierIdentification_ConsultingDefinitionRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_ConsultingDefinitionMLEntity> _ML;
        
        private SLEntityCollection<E_SupplierIdentification_ConsultingDefinitionSLEntity, E_SupplierIdentification_ConsultingDefinitionSLMLEntity> _SL;
        
        private GridEntityCollection<E_SupplierIdentification_ConsultingDefinition_TAGS1Entity, E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity> _E_SupplierIdentification_ConsultingDefinition_TAGS1;
        
        public E_SupplierIdentification_ConsultingDefinitionEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_ConsultingDefinitionMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_ConsultingDefinitionVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDEntity, E_SupplierIdentification_ConsultingDefinitionRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDCEntity, E_SupplierIdentification_ConsultingDefinitionRDCMLEntity>();
            this.E_SupplierIdentification_ConsultingDefinition_TAGS1 = new GridEntityCollection<E_SupplierIdentification_ConsultingDefinition_TAGS1Entity, E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity>();
            this.E_SupplierIdentification_ConsultingDefinition_TAGS1.MLEntityEnabled = true;
            this.E_SupplierIdentification_ConsultingDefinition_TAGS1.SLEntityEnabled = false;
            this.SL = new SLEntityCollection<E_SupplierIdentification_ConsultingDefinitionSLEntity, E_SupplierIdentification_ConsultingDefinitionSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="ACTIVITY", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> ACTIVITY {
            get {
                return this._ACTIVITY;
            }
            set {
                this._ACTIVITY = value;
            }
        }
        
        public E_SupplierIdentification_ConsultingDefinitionVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDEntity, E_SupplierIdentification_ConsultingDefinitionRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_ConsultingDefinitionRDCEntity, E_SupplierIdentification_ConsultingDefinitionRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_ConsultingDefinitionMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_SupplierIdentification_ConsultingDefinitionSLEntity, E_SupplierIdentification_ConsultingDefinitionSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
        
        public GridEntityCollection<E_SupplierIdentification_ConsultingDefinition_TAGS1Entity, E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity> E_SupplierIdentification_ConsultingDefinition_TAGS1 {
            get {
                return this._E_SupplierIdentification_ConsultingDefinition_TAGS1;
            }
            set {
                this._E_SupplierIdentification_ConsultingDefinition_TAGS1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionML")]
    public class E_SupplierIdentification_ConsultingDefinitionMLEntity : MLEntity<E_SupplierIdentification_ConsultingDefinitionMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _CONSULTINGFEES;
        
        private Bimser.Framework.Domain.DataField<string> _SYSTEMNAME1;
        
        private Bimser.Framework.Domain.DataField<string> _CONSULTANCYNAME;
        
        [ColumnOptionsAttribute(Name="CONSULTINGFEES", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> CONSULTINGFEES {
            get {
                return this._CONSULTINGFEES;
            }
            set {
                this._CONSULTINGFEES = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="SYSTEMNAME1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SYSTEMNAME1 {
            get {
                return this._SYSTEMNAME1;
            }
            set {
                this._SYSTEMNAME1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="CONSULTANCYNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> CONSULTANCYNAME {
            get {
                return this._CONSULTANCYNAME;
            }
            set {
                this._CONSULTANCYNAME = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionSL")]
    public class E_SupplierIdentification_ConsultingDefinitionSLEntity : SLEntity<E_SupplierIdentification_ConsultingDefinitionSLEntity, E_SupplierIdentification_ConsultingDefinitionSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionSLML")]
    public class E_SupplierIdentification_ConsultingDefinitionSLMLEntity : SLMLEntity<E_SupplierIdentification_ConsultingDefinitionSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition_TAGS1")]
    public class E_SupplierIdentification_ConsultingDefinition_TAGS1Entity : GridEntity<E_SupplierIdentification_ConsultingDefinition_TAGS1Entity, E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity> {
        
        public E_SupplierIdentification_ConsultingDefinition_TAGS1Entity() {
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition_TAGS1ML")]
    public class E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity : GridMLEntity<E_SupplierIdentification_ConsultingDefinition_TAGS1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _NewColumn1;
        
        [ColumnOptionsAttribute(Name="NewColumn1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> NewColumn1 {
            get {
                return this._NewColumn1;
            }
            set {
                this._NewColumn1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition_TAGS1SL")]
    public class E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity : GridSLEntity<E_SupplierIdentification_ConsultingDefinition_TAGS1SLEntity, E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinition_TAGS1SLML")]
    public class E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity : GridSLMLEntity<E_SupplierIdentification_ConsultingDefinition_TAGS1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionVR")]
    public class E_SupplierIdentification_ConsultingDefinitionVREntity : VersionEntity<E_SupplierIdentification_ConsultingDefinitionVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionRDC")]
    public class E_SupplierIdentification_ConsultingDefinitionRDCEntity : RDCEntity<E_SupplierIdentification_ConsultingDefinitionRDCEntity, E_SupplierIdentification_ConsultingDefinitionRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionRDCML")]
    public class E_SupplierIdentification_ConsultingDefinitionRDCMLEntity : RDCMLEntity<E_SupplierIdentification_ConsultingDefinitionRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionRD")]
    public class E_SupplierIdentification_ConsultingDefinitionRDEntity : RDEntity<E_SupplierIdentification_ConsultingDefinitionRDEntity, E_SupplierIdentification_ConsultingDefinitionRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_ConsultingDefinitionRDML")]
    public class E_SupplierIdentification_ConsultingDefinitionRDMLEntity : RDMLEntity<E_SupplierIdentification_ConsultingDefinitionRDMLEntity> {
    }
}




