//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescription")]
    public class E_SupplierIdentification_PartnerDetailDescriptionEntity : FormEntity<E_SupplierIdentification_PartnerDetailDescriptionEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _AccountantNumber;
        
        private Bimser.Framework.Domain.DataField<string> _FAXNUMBER;
        
        private Bimser.Framework.Domain.DataField<string> _FIRMNUMBER;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _WORKERCOUNT;
        
        private Bimser.Framework.Domain.DataField<string> _MaskInput3;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _IMAGEID;
        
        private E_SupplierIdentification_PartnerDetailDescriptionVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDEntity, E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDCEntity, E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionMLEntity> _ML;
        
        private SLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionSLEntity, E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity> _SL;
        
        public E_SupplierIdentification_PartnerDetailDescriptionEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_PartnerDetailDescriptionVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDEntity, E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDCEntity, E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity>();
            this.SL = new SLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionSLEntity, E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="AccountantNumber", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> AccountantNumber {
            get {
                return this._AccountantNumber;
            }
            set {
                this._AccountantNumber = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="FAXNUMBER", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> FAXNUMBER {
            get {
                return this._FAXNUMBER;
            }
            set {
                this._FAXNUMBER = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="FIRMNUMBER", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> FIRMNUMBER {
            get {
                return this._FIRMNUMBER;
            }
            set {
                this._FIRMNUMBER = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="WORKERCOUNT", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> WORKERCOUNT {
            get {
                return this._WORKERCOUNT;
            }
            set {
                this._WORKERCOUNT = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MaskInput3", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> MaskInput3 {
            get {
                return this._MaskInput3;
            }
            set {
                this._MaskInput3 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="IMAGEID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> IMAGEID {
            get {
                return this._IMAGEID;
            }
            set {
                this._IMAGEID = value;
            }
        }
        
        public E_SupplierIdentification_PartnerDetailDescriptionVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDEntity, E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionRDCEntity, E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_SupplierIdentification_PartnerDetailDescriptionSLEntity, E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionML")]
    public class E_SupplierIdentification_PartnerDetailDescriptionMLEntity : MLEntity<E_SupplierIdentification_PartnerDetailDescriptionMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _PARTNERCOMPANYNAME;
        
        private Bimser.Framework.Domain.DataField<string> _STREET;
        
        private Bimser.Framework.Domain.DataField<string> _PARTNERWEBADDRESS;
        
        private Bimser.Framework.Domain.DataField<string> _DISTRICT;
        
        private Bimser.Framework.Domain.DataField<string> _PROVINCE;
        
        private Bimser.Framework.Domain.DataField<string> _WEBSITE1;
        
        private Bimser.Framework.Domain.DataField<string> _SOCIALMEDIA;
        
        private Bimser.Framework.Domain.DataField<string> _NEIGHBOURHOOD;
        
        private Bimser.Framework.Domain.DataField<string> _ACCOUNTANTADDRESS;
        
        private Bimser.Framework.Domain.DataField<string> _HTMLDETAIL;
        
        private Bimser.Framework.Domain.DataField<string> _ADDRESSNUMBER;
        
        private Bimser.Framework.Domain.DataField<string> _COVERLETTER;
        
        [ColumnOptionsAttribute(Name="PARTNERCOMPANYNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> PARTNERCOMPANYNAME {
            get {
                return this._PARTNERCOMPANYNAME;
            }
            set {
                this._PARTNERCOMPANYNAME = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="STREET", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> STREET {
            get {
                return this._STREET;
            }
            set {
                this._STREET = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="PARTNERWEBADDRESS", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> PARTNERWEBADDRESS {
            get {
                return this._PARTNERWEBADDRESS;
            }
            set {
                this._PARTNERWEBADDRESS = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DISTRICT", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> DISTRICT {
            get {
                return this._DISTRICT;
            }
            set {
                this._DISTRICT = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="PROVINCE", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> PROVINCE {
            get {
                return this._PROVINCE;
            }
            set {
                this._PROVINCE = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="WEBSITE1", Mandatory=false, Size=100)]
        public Bimser.Framework.Domain.DataField<string> WEBSITE1 {
            get {
                return this._WEBSITE1;
            }
            set {
                this._WEBSITE1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="SOCIALMEDIA", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SOCIALMEDIA {
            get {
                return this._SOCIALMEDIA;
            }
            set {
                this._SOCIALMEDIA = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NEIGHBOURHOOD", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> NEIGHBOURHOOD {
            get {
                return this._NEIGHBOURHOOD;
            }
            set {
                this._NEIGHBOURHOOD = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ACCOUNTANTADDRESS", Mandatory=false, Size=1000)]
        public Bimser.Framework.Domain.DataField<string> ACCOUNTANTADDRESS {
            get {
                return this._ACCOUNTANTADDRESS;
            }
            set {
                this._ACCOUNTANTADDRESS = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="HTMLDETAIL", Mandatory=false, Size=2147483647)]
        public Bimser.Framework.Domain.DataField<string> HTMLDETAIL {
            get {
                return this._HTMLDETAIL;
            }
            set {
                this._HTMLDETAIL = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ADDRESSNUMBER", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> ADDRESSNUMBER {
            get {
                return this._ADDRESSNUMBER;
            }
            set {
                this._ADDRESSNUMBER = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="COVERLETTER", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> COVERLETTER {
            get {
                return this._COVERLETTER;
            }
            set {
                this._COVERLETTER = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionSL")]
    public class E_SupplierIdentification_PartnerDetailDescriptionSLEntity : SLEntity<E_SupplierIdentification_PartnerDetailDescriptionSLEntity, E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionSLML")]
    public class E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity : SLMLEntity<E_SupplierIdentification_PartnerDetailDescriptionSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionVR")]
    public class E_SupplierIdentification_PartnerDetailDescriptionVREntity : VersionEntity<E_SupplierIdentification_PartnerDetailDescriptionVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionRDC")]
    public class E_SupplierIdentification_PartnerDetailDescriptionRDCEntity : RDCEntity<E_SupplierIdentification_PartnerDetailDescriptionRDCEntity, E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionRDCML")]
    public class E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity : RDCMLEntity<E_SupplierIdentification_PartnerDetailDescriptionRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionRD")]
    public class E_SupplierIdentification_PartnerDetailDescriptionRDEntity : RDEntity<E_SupplierIdentification_PartnerDetailDescriptionRDEntity, E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerDetailDescriptionRDML")]
    public class E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity : RDMLEntity<E_SupplierIdentification_PartnerDetailDescriptionRDMLEntity> {
    }
}




