//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenu")]
    public class E_SupplierIdentification_PartnerMainMenuEntity : FormEntity<E_SupplierIdentification_PartnerMainMenuEntity> {
        
        private E_SupplierIdentification_PartnerMainMenuVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_PartnerMainMenuRDEntity, E_SupplierIdentification_PartnerMainMenuRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_PartnerMainMenuRDCEntity, E_SupplierIdentification_PartnerMainMenuRDCMLEntity> _RDC;
        
        public E_SupplierIdentification_PartnerMainMenuEntity() {
            this.VersionEntity = new E_SupplierIdentification_PartnerMainMenuVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_PartnerMainMenuRDEntity, E_SupplierIdentification_PartnerMainMenuRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_PartnerMainMenuRDCEntity, E_SupplierIdentification_PartnerMainMenuRDCMLEntity>();
        }
        
        public E_SupplierIdentification_PartnerMainMenuVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_PartnerMainMenuRDEntity, E_SupplierIdentification_PartnerMainMenuRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_PartnerMainMenuRDCEntity, E_SupplierIdentification_PartnerMainMenuRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenuVR")]
    public class E_SupplierIdentification_PartnerMainMenuVREntity : VersionEntity<E_SupplierIdentification_PartnerMainMenuVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenuRDC")]
    public class E_SupplierIdentification_PartnerMainMenuRDCEntity : RDCEntity<E_SupplierIdentification_PartnerMainMenuRDCEntity, E_SupplierIdentification_PartnerMainMenuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenuRDCML")]
    public class E_SupplierIdentification_PartnerMainMenuRDCMLEntity : RDCMLEntity<E_SupplierIdentification_PartnerMainMenuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenuRD")]
    public class E_SupplierIdentification_PartnerMainMenuRDEntity : RDEntity<E_SupplierIdentification_PartnerMainMenuRDEntity, E_SupplierIdentification_PartnerMainMenuRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerMainMenuRDML")]
    public class E_SupplierIdentification_PartnerMainMenuRDMLEntity : RDMLEntity<E_SupplierIdentification_PartnerMainMenuRDMLEntity> {
    }
}




