//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEdit")]
    public class E_SupplierIdentification_SolutionEditEntity : FormEntity<E_SupplierIdentification_SolutionEditEntity> {
        
        private E_SupplierIdentification_SolutionEditVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_SolutionEditRDEntity, E_SupplierIdentification_SolutionEditRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_SolutionEditRDCEntity, E_SupplierIdentification_SolutionEditRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_SolutionEditMLEntity> _ML;
        
        public E_SupplierIdentification_SolutionEditEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_SolutionEditMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_SolutionEditVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_SolutionEditRDEntity, E_SupplierIdentification_SolutionEditRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_SolutionEditRDCEntity, E_SupplierIdentification_SolutionEditRDCMLEntity>();
        }
        
        public E_SupplierIdentification_SolutionEditVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_SolutionEditRDEntity, E_SupplierIdentification_SolutionEditRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_SolutionEditRDCEntity, E_SupplierIdentification_SolutionEditRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_SolutionEditMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditML")]
    public class E_SupplierIdentification_SolutionEditMLEntity : MLEntity<E_SupplierIdentification_SolutionEditMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _SOLUTIONNAME;
        
        private Bimser.Framework.Domain.DataField<string> _SolutionDefinition;
        
        [ColumnOptionsAttribute(Name="SOLUTIONNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> SOLUTIONNAME {
            get {
                return this._SOLUTIONNAME;
            }
            set {
                this._SOLUTIONNAME = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="SolutionDefinition", Mandatory=false, Size=5000)]
        public Bimser.Framework.Domain.DataField<string> SolutionDefinition {
            get {
                return this._SolutionDefinition;
            }
            set {
                this._SolutionDefinition = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditVR")]
    public class E_SupplierIdentification_SolutionEditVREntity : VersionEntity<E_SupplierIdentification_SolutionEditVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditRDC")]
    public class E_SupplierIdentification_SolutionEditRDCEntity : RDCEntity<E_SupplierIdentification_SolutionEditRDCEntity, E_SupplierIdentification_SolutionEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditRDCML")]
    public class E_SupplierIdentification_SolutionEditRDCMLEntity : RDCMLEntity<E_SupplierIdentification_SolutionEditRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditRD")]
    public class E_SupplierIdentification_SolutionEditRDEntity : RDEntity<E_SupplierIdentification_SolutionEditRDEntity, E_SupplierIdentification_SolutionEditRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SolutionEditRDML")]
    public class E_SupplierIdentification_SolutionEditRDMLEntity : RDMLEntity<E_SupplierIdentification_SolutionEditRDMLEntity> {
    }
}




