//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUser")]
    public class E_SupplierIdentification_PartnerUserEntity : FormEntity<E_SupplierIdentification_PartnerUserEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _ACTIVITY1;
        
        private Bimser.Framework.Domain.DataField<string> _USERPHONENUMBER;
        
        private E_SupplierIdentification_PartnerUserVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_PartnerUserRDEntity, E_SupplierIdentification_PartnerUserRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_PartnerUserRDCEntity, E_SupplierIdentification_PartnerUserRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_PartnerUserMLEntity> _ML;
        
        private SLEntityCollection<E_SupplierIdentification_PartnerUserSLEntity, E_SupplierIdentification_PartnerUserSLMLEntity> _SL;
        
        public E_SupplierIdentification_PartnerUserEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_PartnerUserMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_PartnerUserVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_PartnerUserRDEntity, E_SupplierIdentification_PartnerUserRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_PartnerUserRDCEntity, E_SupplierIdentification_PartnerUserRDCMLEntity>();
            this.SL = new SLEntityCollection<E_SupplierIdentification_PartnerUserSLEntity, E_SupplierIdentification_PartnerUserSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="ACTIVITY1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> ACTIVITY1 {
            get {
                return this._ACTIVITY1;
            }
            set {
                this._ACTIVITY1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="USERPHONENUMBER", Mandatory=false, Size=20)]
        public Bimser.Framework.Domain.DataField<string> USERPHONENUMBER {
            get {
                return this._USERPHONENUMBER;
            }
            set {
                this._USERPHONENUMBER = value;
            }
        }
        
        public E_SupplierIdentification_PartnerUserVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_PartnerUserRDEntity, E_SupplierIdentification_PartnerUserRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_PartnerUserRDCEntity, E_SupplierIdentification_PartnerUserRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_PartnerUserMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_SupplierIdentification_PartnerUserSLEntity, E_SupplierIdentification_PartnerUserSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserML")]
    public class E_SupplierIdentification_PartnerUserMLEntity : MLEntity<E_SupplierIdentification_PartnerUserMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _USERPASSWORD;
        
        private Bimser.Framework.Domain.DataField<string> _USERTITLE;
        
        private Bimser.Framework.Domain.DataField<string> _USERSURNAME;
        
        private Bimser.Framework.Domain.DataField<string> _USEREMAIL;
        
        private Bimser.Framework.Domain.DataField<string> _USERNAME;
        
        [ColumnOptionsAttribute(Name="USERPASSWORD", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> USERPASSWORD {
            get {
                return this._USERPASSWORD;
            }
            set {
                this._USERPASSWORD = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="USERTITLE", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> USERTITLE {
            get {
                return this._USERTITLE;
            }
            set {
                this._USERTITLE = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="USERSURNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> USERSURNAME {
            get {
                return this._USERSURNAME;
            }
            set {
                this._USERSURNAME = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="USEREMAIL", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> USEREMAIL {
            get {
                return this._USEREMAIL;
            }
            set {
                this._USEREMAIL = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="USERNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> USERNAME {
            get {
                return this._USERNAME;
            }
            set {
                this._USERNAME = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserSL")]
    public class E_SupplierIdentification_PartnerUserSLEntity : SLEntity<E_SupplierIdentification_PartnerUserSLEntity, E_SupplierIdentification_PartnerUserSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserSLML")]
    public class E_SupplierIdentification_PartnerUserSLMLEntity : SLMLEntity<E_SupplierIdentification_PartnerUserSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserVR")]
    public class E_SupplierIdentification_PartnerUserVREntity : VersionEntity<E_SupplierIdentification_PartnerUserVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserRDC")]
    public class E_SupplierIdentification_PartnerUserRDCEntity : RDCEntity<E_SupplierIdentification_PartnerUserRDCEntity, E_SupplierIdentification_PartnerUserRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserRDCML")]
    public class E_SupplierIdentification_PartnerUserRDCMLEntity : RDCMLEntity<E_SupplierIdentification_PartnerUserRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserRD")]
    public class E_SupplierIdentification_PartnerUserRDEntity : RDEntity<E_SupplierIdentification_PartnerUserRDEntity, E_SupplierIdentification_PartnerUserRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_PartnerUserRDML")]
    public class E_SupplierIdentification_PartnerUserRDMLEntity : RDMLEntity<E_SupplierIdentification_PartnerUserRDMLEntity> {
    }
}




