//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace SupplierIdentification.Entities {
    
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage")]
    public class E_SupplierIdentification_SupplyPageEntity : FormEntity<E_SupplierIdentification_SupplyPageEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _ACTIVITY2;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _HOTFIXVALUE;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _CheckBox1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _NumberBox1;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<bool>> _ACTIVITY;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker1_Start;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker1_End;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker2_Start;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker2_End;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker3_Start;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _DateRangePicker3_End;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _MAJORVALUE;
        
        private Bimser.Framework.Domain.DataField<string> _Signature1;
        
        private Bimser.Framework.Domain.DataField<string> _Signature2;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _MINORVALUE;
        
        private E_SupplierIdentification_SupplyPageVREntity _VersionEntity;
        
        private RDEntityCollection<E_SupplierIdentification_SupplyPageRDEntity, E_SupplierIdentification_SupplyPageRDMLEntity> _RD;
        
        private RDCEntityCollection<E_SupplierIdentification_SupplyPageRDCEntity, E_SupplierIdentification_SupplyPageRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_SupplierIdentification_SupplyPageMLEntity> _ML;
        
        private SLEntityCollection<E_SupplierIdentification_SupplyPageSLEntity, E_SupplierIdentification_SupplyPageSLMLEntity> _SL;
        
        private GridEntityCollection<E_SupplierIdentification_SupplyPage_TAGS1Entity, E_SupplierIdentification_SupplyPage_TAGS1MLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity> _E_SupplierIdentification_SupplyPage_TAGS1;
        
        private GridEntityCollection<E_SupplierIdentification_SupplyPage_PROPERTIES1Entity, E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity> _E_SupplierIdentification_SupplyPage_PROPERTIES1;
        
        public E_SupplierIdentification_SupplyPageEntity() {
            this.ML = new MLEntityCollection<E_SupplierIdentification_SupplyPageMLEntity>();
            this.VersionEntity = new E_SupplierIdentification_SupplyPageVREntity();
            this.RD = new RDEntityCollection<E_SupplierIdentification_SupplyPageRDEntity, E_SupplierIdentification_SupplyPageRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_SupplierIdentification_SupplyPageRDCEntity, E_SupplierIdentification_SupplyPageRDCMLEntity>();
            this.E_SupplierIdentification_SupplyPage_TAGS1 = new GridEntityCollection<E_SupplierIdentification_SupplyPage_TAGS1Entity, E_SupplierIdentification_SupplyPage_TAGS1MLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity>();
            this.E_SupplierIdentification_SupplyPage_TAGS1.MLEntityEnabled = false;
            this.E_SupplierIdentification_SupplyPage_TAGS1.SLEntityEnabled = false;
            this.E_SupplierIdentification_SupplyPage_PROPERTIES1 = new GridEntityCollection<E_SupplierIdentification_SupplyPage_PROPERTIES1Entity, E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity>();
            this.E_SupplierIdentification_SupplyPage_PROPERTIES1.MLEntityEnabled = true;
            this.E_SupplierIdentification_SupplyPage_PROPERTIES1.SLEntityEnabled = false;
            this.SL = new SLEntityCollection<E_SupplierIdentification_SupplyPageSLEntity, E_SupplierIdentification_SupplyPageSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="ACTIVITY2", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> ACTIVITY2 {
            get {
                return this._ACTIVITY2;
            }
            set {
                this._ACTIVITY2 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="HOTFIXVALUE", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> HOTFIXVALUE {
            get {
                return this._HOTFIXVALUE;
            }
            set {
                this._HOTFIXVALUE = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="CheckBox1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> CheckBox1 {
            get {
                return this._CheckBox1;
            }
            set {
                this._CheckBox1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="NumberBox1", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> NumberBox1 {
            get {
                return this._NumberBox1;
            }
            set {
                this._NumberBox1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ACTIVITY", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<bool>> ACTIVITY {
            get {
                return this._ACTIVITY;
            }
            set {
                this._ACTIVITY = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker1_Start", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker1_Start {
            get {
                return this._DateRangePicker1_Start;
            }
            set {
                this._DateRangePicker1_Start = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker1_End", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker1_End {
            get {
                return this._DateRangePicker1_End;
            }
            set {
                this._DateRangePicker1_End = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker2_Start", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker2_Start {
            get {
                return this._DateRangePicker2_Start;
            }
            set {
                this._DateRangePicker2_Start = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker2_End", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker2_End {
            get {
                return this._DateRangePicker2_End;
            }
            set {
                this._DateRangePicker2_End = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker3_Start", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker3_Start {
            get {
                return this._DateRangePicker3_Start;
            }
            set {
                this._DateRangePicker3_Start = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="DateRangePicker3_End", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> DateRangePicker3_End {
            get {
                return this._DateRangePicker3_End;
            }
            set {
                this._DateRangePicker3_End = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MAJORVALUE", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> MAJORVALUE {
            get {
                return this._MAJORVALUE;
            }
            set {
                this._MAJORVALUE = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="Signature1", Mandatory=false, Size=2147483647)]
        public Bimser.Framework.Domain.DataField<string> Signature1 {
            get {
                return this._Signature1;
            }
            set {
                this._Signature1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="Signature2", Mandatory=false, Size=2147483647)]
        public Bimser.Framework.Domain.DataField<string> Signature2 {
            get {
                return this._Signature2;
            }
            set {
                this._Signature2 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="MINORVALUE", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> MINORVALUE {
            get {
                return this._MINORVALUE;
            }
            set {
                this._MINORVALUE = value;
            }
        }
        
        public E_SupplierIdentification_SupplyPageVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_SupplierIdentification_SupplyPageRDEntity, E_SupplierIdentification_SupplyPageRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_SupplierIdentification_SupplyPageRDCEntity, E_SupplierIdentification_SupplyPageRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_SupplierIdentification_SupplyPageMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_SupplierIdentification_SupplyPageSLEntity, E_SupplierIdentification_SupplyPageSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
        
        public GridEntityCollection<E_SupplierIdentification_SupplyPage_TAGS1Entity, E_SupplierIdentification_SupplyPage_TAGS1MLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity> E_SupplierIdentification_SupplyPage_TAGS1 {
            get {
                return this._E_SupplierIdentification_SupplyPage_TAGS1;
            }
            set {
                this._E_SupplierIdentification_SupplyPage_TAGS1 = value;
            }
        }
        
        public GridEntityCollection<E_SupplierIdentification_SupplyPage_PROPERTIES1Entity, E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity> E_SupplierIdentification_SupplyPage_PROPERTIES1 {
            get {
                return this._E_SupplierIdentification_SupplyPage_PROPERTIES1;
            }
            set {
                this._E_SupplierIdentification_SupplyPage_PROPERTIES1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageML")]
    public class E_SupplierIdentification_SupplyPageMLEntity : MLEntity<E_SupplierIdentification_SupplyPageMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _COMPATIBLEVERSION;
        
        private Bimser.Framework.Domain.DataField<string> _SUMMARYINFORMATION;
        
        private Bimser.Framework.Domain.DataField<string> _HTMLDETAILS;
        
        [ColumnOptionsAttribute(Name="COMPATIBLEVERSION", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> COMPATIBLEVERSION {
            get {
                return this._COMPATIBLEVERSION;
            }
            set {
                this._COMPATIBLEVERSION = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="SUMMARYINFORMATION", Mandatory=false, Size=1000)]
        public Bimser.Framework.Domain.DataField<string> SUMMARYINFORMATION {
            get {
                return this._SUMMARYINFORMATION;
            }
            set {
                this._SUMMARYINFORMATION = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="HTMLDETAILS", Mandatory=false, Size=2147483647)]
        public Bimser.Framework.Domain.DataField<string> HTMLDETAILS {
            get {
                return this._HTMLDETAILS;
            }
            set {
                this._HTMLDETAILS = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageSL")]
    public class E_SupplierIdentification_SupplyPageSLEntity : SLEntity<E_SupplierIdentification_SupplyPageSLEntity, E_SupplierIdentification_SupplyPageSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageSLML")]
    public class E_SupplierIdentification_SupplyPageSLMLEntity : SLMLEntity<E_SupplierIdentification_SupplyPageSLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_TAGS1")]
    public class E_SupplierIdentification_SupplyPage_TAGS1Entity : GridEntity<E_SupplierIdentification_SupplyPage_TAGS1Entity, E_SupplierIdentification_SupplyPage_TAGS1MLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity> {
        
        public E_SupplierIdentification_SupplyPage_TAGS1Entity() {
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_TAGS1ML")]
    public class E_SupplierIdentification_SupplyPage_TAGS1MLEntity : GridMLEntity<E_SupplierIdentification_SupplyPage_TAGS1MLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_TAGS1SL")]
    public class E_SupplierIdentification_SupplyPage_TAGS1SLEntity : GridSLEntity<E_SupplierIdentification_SupplyPage_TAGS1SLEntity, E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_TAGS1SLML")]
    public class E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity : GridSLMLEntity<E_SupplierIdentification_SupplyPage_TAGS1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_PROPERTIES1")]
    public class E_SupplierIdentification_SupplyPage_PROPERTIES1Entity : GridEntity<E_SupplierIdentification_SupplyPage_PROPERTIES1Entity, E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity> {
        
        public E_SupplierIdentification_SupplyPage_PROPERTIES1Entity() {
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_PROPERTIES1ML")]
    public class E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity : GridMLEntity<E_SupplierIdentification_SupplyPage_PROPERTIES1MLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _NewColumn1;
        
        [ColumnOptionsAttribute(Name="NewColumn1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> NewColumn1 {
            get {
                return this._NewColumn1;
            }
            set {
                this._NewColumn1 = value;
            }
        }
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_PROPERTIES1SL")]
    public class E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity : GridSLEntity<E_SupplierIdentification_SupplyPage_PROPERTIES1SLEntity, E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPage_PROPERTIES1SLML")]
    public class E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity : GridSLMLEntity<E_SupplierIdentification_SupplyPage_PROPERTIES1SLMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageVR")]
    public class E_SupplierIdentification_SupplyPageVREntity : VersionEntity<E_SupplierIdentification_SupplyPageVREntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageRDC")]
    public class E_SupplierIdentification_SupplyPageRDCEntity : RDCEntity<E_SupplierIdentification_SupplyPageRDCEntity, E_SupplierIdentification_SupplyPageRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageRDCML")]
    public class E_SupplierIdentification_SupplyPageRDCMLEntity : RDCMLEntity<E_SupplierIdentification_SupplyPageRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageRD")]
    public class E_SupplierIdentification_SupplyPageRDEntity : RDEntity<E_SupplierIdentification_SupplyPageRDEntity, E_SupplierIdentification_SupplyPageRDMLEntity> {
    }
    
    [TableOptions(TableName="E_SupplierIdentification_SupplyPageRDML")]
    public class E_SupplierIdentification_SupplyPageRDMLEntity : RDMLEntity<E_SupplierIdentification_SupplyPageRDMLEntity> {
    }
}




